paras:
  samtools: /data/software/bin/samtools
  bedtools: /data/software/bedtools2/bin/bedtools
  lastal: /data/liangfan/pipeline/sv/bin/lastal
  hg38: /data/xieshang/database/ftp.1000genomes.ebi.ac.uk/vol1/ftp/technical/reference/GRCh38_reference_genome/GRCh38_full_analysis_set_plus_decoy_hla.fa
  hg19: /data/xieshang/database/ftp.1000genomes.ebi.ac.uk/vol1/ftp/technical/reference/human_g1k_v37.fasta

bwa:
  cmd: ''
  memory: 16g
  thread: 16
  queue: all.q

last:
  cmd: 'lastal -P {thread} -Q1 {last_db} {fq} -p {params} | last-split > {output}.last.maf && maf-convert -d sam {output}.last.maf | {samtools} view -bS - | {samtools} sort -m {memory} -o {output} - && rm  {output}.last.maf'
  memory: 16G
  thread: 8
  queue: all.q

ngmlr:
  cmd: 'ngmlr -t {thread} -x ont -r {ref} -q {fq} | {samtools} sort -m {memory} -o {output} -'
  memory: 16g
  thread: 8
  queue: all.q

merge_bam:
    cmd: '{samtools} merge -f {output} {input_list}'
    memory: 1g
    thread: 1
    queue: all.q

sniffles:
  cmd: '
    sniffles
    --report_BND
    --ignore_sd
    -q 0
    --genotype
    -n  10
    -t 20
    -l 50
    -s 1
    -m {bam}
    -v {output}'
  memory: 16g
  thread: 8
  queue: all.q

